<?php
include('verificar_admin.php');
/*
  PT-PT: Registo de artigo com envio de imagem.

         Defeitos corrigidos:
         1. Execucao remota de codigo. O tipo era lido de $_FILES[...]['type'],
            que vem do cabecalho enviado pelo cliente e e trivial de forjar, e o
            nome do ficheiro era usado tal e qual. Bastava enviar "evil.php"
            com Content-Type: image/jpeg para escrever PHP dentro do site e
            depois pedi-lo pelo browser.
         2. $pasta_imagens nunca foi definida, pelo que o destino era montado a
            partir de uma variavel vazia.
         3. O valor de retorno de move_uploaded_file() era ignorado: uma copia
            falhada continuava a inserir a linha na base de dados.
         4. $_POST/$_REQUEST entravam sem escape no SQL.

         O tipo passa a ser determinado pelo conteudo, com getimagesize(), e o
         nome no disco passa a ser gerado por nos -- nada do que o cliente
         escreve chega ao sistema de ficheiros.

  EN-UK: Article registration with image upload.

         Fixed: remote code execution (the MIME type came from a client-supplied
         header and the client's filename was used verbatim, so uploading
         "evil.php" as image/jpeg wrote PHP into the site); an undefined
         $pasta_imagens; an ignored move_uploaded_file() return value; and
         unescaped $_POST/$_REQUEST reaching the SQL.

         The type is now decided by inspecting the content with getimagesize(),
         and the on-disk name is generated by us -- nothing the client writes
         reaches the filesystem.
*/
include('ligacao_db.php');

// PT-PT: Destino explicito, e so extensoes que nunca sao executadas.
// EN-UK: Explicit destination, and only extensions that are never executed.
$pasta_imagens = __DIR__ . '/pasta_imagens/';
$tamanho_maximo = 350 * 1024;
$tipos_permitidos = array(
    IMAGETYPE_JPEG => '.jpg',
    IMAGETYPE_PNG  => '.png',
    IMAGETYPE_GIF  => '.gif',
);

$erros = array();

if (!isset($_FILES['imagem']) || $_FILES['imagem']['error'] !== UPLOAD_ERR_OK) {
    $erros[] = "Nao foi recebido nenhum ficheiro de imagem valido.";
} elseif ($_FILES['imagem']['size'] > $tamanho_maximo) {
    $erros[] = "O ficheiro submetido nao pode ultrapassar os 350 Kb.";
} else {
    // PT-PT: O tipo vem do conteudo, nao do cabecalho. getimagesize() devolve
    //        false para tudo o que nao seja uma imagem real.
    // EN-UK: The type comes from the content, not the header. getimagesize()
    //        returns false for anything that is not a real image.
    $info = @getimagesize($_FILES['imagem']['tmp_name']);
    if ($info === false || !isset($tipos_permitidos[$info[2]])) {
        $erros[] = "O ficheiro submetido nao e uma imagem JPEG, PNG ou GIF.";
    }
}

if (!$erros) {
    $extensao = $tipos_permitidos[$info[2]];

    // PT-PT: Nome gerado por nos. O nome do cliente nunca toca no disco.
    // EN-UK: Name generated by us. The client's name never touches the disk.
    $img_nome = bin2hex(openssl_random_pseudo_bytes(16)) . $extensao;
    $local_final = $pasta_imagens . $img_nome;

    if (!is_dir($pasta_imagens)) {
        mkdir($pasta_imagens, 0755, true);
    }

    if (!move_uploaded_file($_FILES['imagem']['tmp_name'], $local_final)) {
        $erros[] = "Nao foi possivel guardar a imagem no servidor.";
    }
}

if ($erros) {
    echo "<p>Nao foi possivel registar os dados devido a um erro no ficheiro de imagem.";
    foreach ($erros as $erro) {
        echo "<p>" . htmlspecialchars($erro, ENT_QUOTES, 'UTF-8') . "</br>";
    }
    echo "<p><a href=\"menu_admin.php\">Clique aqui para continuar</a>";
    exit;
}

// PT-PT: mysql_* nao tem consultas preparadas; escapar e a mitigacao possivel.
//        preco e stock sao numericos e passam por conversao explicita.
// EN-UK: mysql_* has no prepared statements; escaping is the available
//        mitigation. Price and stock are numeric and are cast explicitly.
$cat_prod = (int) $_POST["cat_prod"];
$preco_prod = (float) $_POST["preco_prod"];
$stock_prod = (int) $_POST["stock_prod"];
$nome_prod = mysql_real_escape_string($_POST["nome_prod"], $ligacao);
$desc_prod = mysql_real_escape_string($_POST["desc_prod"], $ligacao);
$img_nome_sql = mysql_real_escape_string($img_nome, $ligacao);

$sql_regista = "INSERT INTO artigos
    (id_categoria, nome_artigo, descricao_artigo, preco_artigo, stock_artigo, imagem_artigo)
    VALUES ('$cat_prod', '$nome_prod', '$desc_prod', '$preco_prod', '$stock_prod', '$img_nome_sql')";
$consulta = mysql_query($sql_regista, $ligacao);

if (!$consulta) {
    // PT-PT: Nao devolver mysql_error() ao browser -- revela esquema.
    // EN-UK: Do not echo mysql_error() to the browser -- it leaks the schema.
    @unlink($local_final);
    echo "<p>Nao foi possivel registar o artigo.";
    echo "<p><a href=\"menu_admin.php\">Clique aqui para continuar</a>";
    exit;
}

echo "O registo foi efetuado com sucesso! <p>Clique <a href=\"menu_admin.php\"> aqui </a> para continuar";
?>
